version: '3.7'

services:

  postgres:
    container_name: multitools_postgres
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=multitools
      - POSTGRES_USER=vicente
      - POSTGRES_PASSWORD=123456
    security_opt:
      - seccomp:unconfined
    ports:
      - "5432:5432"
    volumes:
      - ../.docker/pgdata:/var/lib/postgresql/data
    networks:
      - multitools_services

networks:
  multitools_services: