CREATE SCHEMA IF NOT EXISTS crudcleanarchddd;

CREATE TABLE IF NOT EXISTS crudcleanarchddd.PRODUCT (
     ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID VARCHAR(255) NOT NULL,

    FOREIGN KEY (CATEGORY_ID) REFERENCES crudcleanarchddd.CATEGORY(ID)
);