CREATE SCHEMA IF NOT EXISTS crudmvc;

CREATE TABLE IF NOT EXISTS crudmvc.OCCUPATION (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DELETED BOOLEAN NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    DELETED_AT TIMESTAMP(6)
);