CREATE SCHEMA IF NOT EXISTS crudmvc;

CREATE SEQUENCE IF NOT EXISTS crudmvc.occupation_id_seq;

CREATE TABLE IF NOT EXISTS crudmvc.OCCUPATION (
    ID BIGINT PRIMARY KEY DEFAULT nextval('crudmvc.occupation_id_seq'),
    NAME VARCHAR(255) NOT NULL,
    DELETED BOOLEAN NOT NULL,
    UPDATED_AT TIMESTAMP(6),
    DELETED_AT TIMESTAMP(6)
);