CREATE SCHEMA IF NOT EXISTS crudmvc;

CREATE SEQUENCE IF NOT EXISTS crudmvc.employee_id_seq;

CREATE TABLE IF NOT EXISTS crudmvc.EMPLOYEE (
    ID BIGINT PRIMARY KEY DEFAULT nextval('crudmvc.employee_id_seq'),
    NAME VARCHAR(255) NOT NULL,
    OCCUPATION_ID BIGINT NOT NULL,

    FOREIGN KEY (OCCUPATION_ID) REFERENCES crudmvc.OCCUPATION(ID)
);

